name: Testat3

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: auschecken
            uses: actions/checkout@v4

          - name: Java auf Server installieren
            uses: actions/setup-java@v4
            with:
                java-version: '17'
                distribution: 'temurin'

          - name: Dateien kompilieren
            run: javac src/Calculator.java src/CalculatorTest.java

          - name: Tests ausf√ºhren
            run: java -cp src CalculatorTest